name: test time workflow
on:  
  workflow_dispatch:

jobs:
  get-tmdb-persons-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get current date
        id: date
        run: echo "::set-output name=cur_datetime::$(date +'%Y-%m-%d-%H_%M_%S')"
      
      - name: Print datetime
        id: printtime
        run: echo "tmdb-person-data-${{ steps.date.outputs.cur_datetime }}"